ingress:
  enabled: true
  extras: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    certmanager.k8s.io/acme-challenge-type: http01
  svcs:
    index_path: /
    blog_service: blog-zigdata-blog
    jupyter_service: jupyter-zigdata-jupyter
    viz_service: viz-zigdata-viz
  hosts:
    - translit.io
    - www.translit.io
    - lab.translit.io
    - viz.translit.io
  tls:
  - hosts:
      - translit.io
      - www.translit.io
      - lab.translit.io
      - viz.translit.io
    secretName: translit-tls