ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/use-regex: "true"
  svcs:
    index_path: /
    blog_service: blog-zigdata-blog
    notebook_path: /(notebook-test/api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/?
    jupyter_service: jupyter-zigdata-jupyter

  hosts:
    - www.zigdata.org
    - zigdata.org
  tls:
  - hosts:
      - www.zigdata.org
      - zigdata.org
    secretName: zigdata-org-tls