apiVersion: v1
data:
  enable-vts-status: "true"
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.3.1
    component: controller
    heritage: Tiller
    release: zigdata-ingress
  name: zigdata-ingress-nginx-ingress-controller
