# Default values for zigdata.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: zigzacks/zigdata
  tag: blog
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""


service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
#    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
#    certmanager.k8s.io/acme-challenge-type: http01
  paths:
    - /
  tls:
  - hosts:
      - zigdata.org
      - www.zigdata.org
    secretName: zigdata-org-tls

resources:
   limits:
    cpu: 500m
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

app:
  reddit:
    user_agent: zarfjohnson

jobs:
  - name: reddit
    image:
      repository: zigzacks/zigdata
      tag: reddit
      pullPolicy: Always
    schedule: "*/30 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    envFrom:
      - secretRef:
          name: reddit-secrets
      - secretRef:
          name: aws-secrets
      - configMapRef:
          name: reddit-envvars
