service:
  enabled: true
  type: ClusterIP
  port: 8989
  targetPort: http

deployment:
  enabled: true
  replicaCount: 1

  image:
    repository: zigzacks/zigdata
    tag: jupyter
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  resources:
     limits:
      cpu: 500m
      memory: 256Mi
     requests:
      cpu: 50m
      memory: 64Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 2Gi
    storageClass: gp2