version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - setup_remote_docker
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "env.yaml" }}
            - v1-dependencies-

      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: docker build -t zigdata .
      - run: docker tag zigdata zigzacks/zigdata:latest
      - run: docker push zigzacks/zigdata

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "env.yaml" }}