apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  AWS_ACCESS_KEY_ID: {{ default "" .Values.app.aws.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .Values.app.aws.secret | b64enc | quote }}